//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.ibm.juwlee.jaxws.client;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.juwlee.jaxws.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CallIt_QNAME = new QName("http://jaxws.juwlee.ibm.com/", "CallIt");
    private final static QName _CallItResponse_QNAME = new QName("http://jaxws.juwlee.ibm.com/", "CallItResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.juwlee.jaxws.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CallIt }
     * 
     */
    public CallIt createCallIt() {
        return new CallIt();
    }

    /**
     * Create an instance of {@link CallItResponse }
     * 
     */
    public CallItResponse createCallItResponse() {
        return new CallItResponse();
    }

    /**
     * Create an instance of {@link TestVO }
     * 
     */
    public TestVO createTestVO() {
        return new TestVO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CallIt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.juwlee.ibm.com/", name = "CallIt")
    public JAXBElement<CallIt> createCallIt(CallIt value) {
        return new JAXBElement<CallIt>(_CallIt_QNAME, CallIt.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CallItResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.juwlee.ibm.com/", name = "CallItResponse")
    public JAXBElement<CallItResponse> createCallItResponse(CallItResponse value) {
        return new JAXBElement<CallItResponse>(_CallItResponse_QNAME, CallItResponse.class, null, value);
    }

}
