//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.ibm.juwlee.jaxws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "VarargsJAXWSCall", targetNamespace = "http://jaxws.juwlee.ibm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VarargsJAXWSCall {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "CallIt")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CallIt", targetNamespace = "http://jaxws.juwlee.ibm.com/", className = "com.ibm.juwlee.jaxws.client.CallIt")
    @ResponseWrapper(localName = "CallItResponse", targetNamespace = "http://jaxws.juwlee.ibm.com/", className = "com.ibm.juwlee.jaxws.client.CallItResponse")
    public Object callIt(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Object> arg0);

}
