//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.ibm.juwlee.jaxws.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "VarargsJAXWSCallService", targetNamespace = "http://jaxws.juwlee.ibm.com/", wsdlLocation = "WEB-INF/wsdl/VarargsJAXWSCallService.wsdl")
public class VarargsJAXWSCallService
    extends Service
{

    private final static URL VARARGSJAXWSCALLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VARARGSJAXWSCALLSERVICE_EXCEPTION;
    private final static QName VARARGSJAXWSCALLSERVICE_QNAME = new QName("http://jaxws.juwlee.ibm.com/", "VarargsJAXWSCallService");

    static {
            VARARGSJAXWSCALLSERVICE_WSDL_LOCATION = com.ibm.juwlee.jaxws.client.VarargsJAXWSCallService.class.getResource("/WEB-INF/wsdl/VarargsJAXWSCallService.wsdl");
        WebServiceException e = null;
        if (VARARGSJAXWSCALLSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/VarargsJAXWSCallService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        VARARGSJAXWSCALLSERVICE_EXCEPTION = e;
    }

    public VarargsJAXWSCallService() {
        super(__getWsdlLocation(), VARARGSJAXWSCALLSERVICE_QNAME);
    }

    public VarargsJAXWSCallService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns VarargsJAXWSCall
     */
    @WebEndpoint(name = "VarargsJAXWSCallPort")
    public VarargsJAXWSCall getVarargsJAXWSCallPort() {
        return super.getPort(new QName("http://jaxws.juwlee.ibm.com/", "VarargsJAXWSCallPort"), VarargsJAXWSCall.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VarargsJAXWSCall
     */
    @WebEndpoint(name = "VarargsJAXWSCallPort")
    public VarargsJAXWSCall getVarargsJAXWSCallPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.juwlee.ibm.com/", "VarargsJAXWSCallPort"), VarargsJAXWSCall.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VARARGSJAXWSCALLSERVICE_EXCEPTION!= null) {
            throw VARARGSJAXWSCALLSERVICE_EXCEPTION;
        }
        return VARARGSJAXWSCALLSERVICE_WSDL_LOCATION;
    }

}
