//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.ibm.juwlee.jaxws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "CallItResponse", namespace = "http://jaxws.juwlee.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallItResponse", namespace = "http://jaxws.juwlee.ibm.com/")
public class CallItResponse {

    @XmlElement(name = "return", namespace = "")
    private Object _return;

    /**
     * 
     * @return
     *     returns Object
     */
    public Object getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(Object _return) {
        this._return = _return;
    }

}
