//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.ibm.juwlee.jaxws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "CallIt", namespace = "http://jaxws.juwlee.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallIt", namespace = "http://jaxws.juwlee.ibm.com/")
public class CallIt {

    @XmlElement(name = "arg0", namespace = "", nillable = true)
    private Object[] arg0;

    /**
     * 
     * @return
     *     returns Object[]
     */
    public Object[] getArg0() {
        return this.arg0;
    }

    /**
     * 
     * @param arg0
     *     the value for the arg0 property
     */
    public void setArg0(Object[] arg0) {
        this.arg0 = arg0;
    }

}
