//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package org.example.wsatwebservice1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "WsatWebService1", targetNamespace = "http://www.example.org/WsatWebService1/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsatWebService1 {


    /**
     * 
     * @param in
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.example.org/WsatWebService1/op1")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "op1", targetNamespace = "http://www.example.org/WsatWebService1/", className = "org.example.wsatwebservice1.Op1")
    @ResponseWrapper(localName = "op1Response", targetNamespace = "http://www.example.org/WsatWebService1/", className = "org.example.wsatwebservice1.Op1Response")
    public String op1(
        @WebParam(name = "in", targetNamespace = "")
        String in);

}
