//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package org.example.wsatwebservice1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "WsatWebService1", targetNamespace = "http://www.example.org/WsatWebService1/", wsdlLocation = "WEB-INF/wsdl/WsatWebService1.wsdl")
public class WsatWebService1_Service
    extends Service
{

    private final static URL WSATWEBSERVICE1_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.example.wsatwebservice1.WsatWebService1_Service.class.getName());

    static {
        URL url = null;
        try {
            url = org.example.wsatwebservice1.WsatWebService1_Service.class.getResource("/WEB-INF/wsdl/WsatWebService1.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/WsatWebService1.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/wsdl/WsatWebService1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSATWEBSERVICE1_WSDL_LOCATION = url;
    }

    public WsatWebService1_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsatWebService1_Service() {
        super(WSATWEBSERVICE1_WSDL_LOCATION, new QName("http://www.example.org/WsatWebService1/", "WsatWebService1"));
    }

    /**
     * 
     * @return
     *     returns WsatWebService1
     */
    @WebEndpoint(name = "WsatWebService1SOAP")
    public WsatWebService1 getWsatWebService1SOAP() {
        return super.getPort(new QName("http://www.example.org/WsatWebService1/", "WsatWebService1SOAP"), WsatWebService1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsatWebService1
     */
    @WebEndpoint(name = "WsatWebService1SOAP")
    public WsatWebService1 getWsatWebService1SOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/WsatWebService1/", "WsatWebService1SOAP"), WsatWebService1.class, features);
    }

}
